#! /bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
$HOME/.config/bspwm/alias.sh
$HOME/.config/bspwm/default.sh

pgrep -x sxhkd > /dev/null || sxhkd &


xrandr --output HDMI-0 --primary --mode 2560x1440 --rate 59.95
#xrandr --output HDMI-0 --right-of DP-4 --mode 1920x1080 --rate 60.00
#xrandr --output DP-2 --left-of DP-4 --mode 1920x1080 --rate 60.00

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Google-chrome desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Rule custom
bspc rule -a Alacritty state=floating
bspc rule -a Pavucontrol state=floating

# themes dracula
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
